"""P2.2 — content digests (ADR-9): SHA-256 over the whole file, one domain.

**T4 — one digest domain, always.** An earlier draft used the git blob id on
clean files and SHA-256 on dirty ones: two domains for one question. The
regression that killed it is fixtured here as a walk —
**untracked → staged → committed → dirty** — over a file whose bytes never
change. Under two domains, `git add` alone turned an in-sync artifact into one
whose bytes the tool claimed not to recognize (ADR-2 row 3, an `error` that
refuses to write). One digest makes that state unreachable.

`WalkTest` is the regression. `NeverTheBlobIdTest` is the assertion that
actually kills the fast path: the blob id is a *different function* — SHA-1
over `blob <len>\\0` plus the content — so asserting the digest is never equal
to it fails the moment anyone reintroduces the optimization, on the very state
(clean and tracked) where the optimization applied.
"""

import hashlib
import os
import shutil
import subprocess
import unittest

import _support as S

S.import_core()

import digest  # noqa: E402


class DigestFixture(unittest.TestCase):
    def setUp(self):
        self.root = S.make_git_repo()
        self.addCleanup(shutil.rmtree, self.root, True)
        self.path = os.path.join(self.root, "AGENTS.md")
        self.body = b"# routing\n\nGenerated by the-steward.\n"
        with open(self.path, "wb") as handle:
            handle.write(self.body)

    def blob_id(self, path):
        result = subprocess.run(
            ["git", "hash-object", path],
            cwd=self.root,
            stdout=subprocess.PIPE,
        )
        return result.stdout.decode("ascii").strip()


class FunctionTest(DigestFixture):
    def test_it_is_sha256_over_the_whole_file(self):
        self.assertEqual(
            hashlib.sha256(self.body).hexdigest(), digest.of_file(self.path)
        )

    def test_bytes_and_file_agree(self):
        self.assertEqual(digest.of_bytes(self.body), digest.of_file(self.path))

    def test_the_empty_file_has_the_empty_digest(self):
        empty = os.path.join(self.root, "empty.md")
        open(empty, "wb").close()
        self.assertEqual(hashlib.sha256(b"").hexdigest(), digest.of_file(empty))

    def test_it_is_lowercase_hex_of_the_length_the_manifest_schema_admits(self):
        value = digest.of_file(self.path)
        self.assertEqual(64, len(value))
        self.assertEqual(value.lower(), value)
        import manifest

        self.assertTrue(manifest._DIGEST.match(value))

    def test_a_file_larger_than_one_read_chunk_hashes_whole(self):
        """Chunked reading is where a truncating bug would hide."""
        big = os.path.join(self.root, "big.md")
        body = (b"0123456789abcdef" * 64 + b"\n") * 400
        self.assertGreater(len(body), digest.READ_CHUNK_BYTES)
        with open(big, "wb") as handle:
            handle.write(body)
        self.assertEqual(hashlib.sha256(body).hexdigest(), digest.of_file(big))

    def test_a_missing_file_raises_rather_than_returning_a_digest(self):
        with self.assertRaises(OSError):
            digest.of_file(os.path.join(self.root, "nope.md"))


class WalkTest(DigestFixture):
    """T4 — untracked → staged → committed → dirty, one digest throughout."""

    def test_one_digest_survives_every_git_state_transition(self):
        expected = hashlib.sha256(self.body).hexdigest()
        seen = []

        seen.append(("untracked", digest.of_file(self.path)))
        S.git(self.root, "add", "AGENTS.md")
        seen.append(("staged", digest.of_file(self.path)))
        S.git(self.root, "commit", "-q", "-m", "add agents")
        seen.append(("committed", digest.of_file(self.path)))

        # "dirty": the working tree carries an uncommitted change, while the
        # artifact's own bytes are untouched. This is the state a clean/dirty
        # fast path branches on.
        with open(os.path.join(self.root, "README.md"), "a", encoding="utf-8") as h:
            h.write("edited\n")
        self.assertNotEqual("", S.porcelain(self.root))
        seen.append(("dirty-tree", digest.of_file(self.path)))

        self.assertEqual(
            [(state, expected) for state, _ in seen],
            seen,
            "the digest changed with the file's git state, not with its bytes",
        )

    def test_the_digest_tracks_bytes_and_only_bytes(self):
        S.git(self.root, "add", "AGENTS.md")
        S.git(self.root, "commit", "-q", "-m", "add agents")
        clean = digest.of_file(self.path)

        with open(self.path, "ab") as handle:
            handle.write(b"hand edit\n")
        edited = digest.of_file(self.path)
        self.assertNotEqual(clean, edited)

        with open(self.path, "wb") as handle:
            handle.write(self.body)
        self.assertEqual(
            clean,
            digest.of_file(self.path),
            "restoring the bytes did not restore the digest",
        )

    def test_it_is_stable_across_a_fresh_clone(self):
        """`mtime` is meaningless after a clone; the digest must not be."""
        S.git(self.root, "add", "AGENTS.md")
        S.git(self.root, "commit", "-q", "-m", "add agents")
        clone = self.root + "-clone"
        self.addCleanup(shutil.rmtree, clone, True)
        S.git(self.root, "clone", "-q", self.root, clone)
        self.assertEqual(
            digest.of_file(self.path),
            digest.of_file(os.path.join(clone, "AGENTS.md")),
        )


class NeverTheBlobIdTest(DigestFixture):
    """The assertion that kills the deleted fast path directly (ADR-9)."""

    def test_the_digest_is_not_the_blob_id_when_the_file_is_clean_and_tracked(self):
        S.git(self.root, "add", "AGENTS.md")
        S.git(self.root, "commit", "-q", "-m", "add agents")
        self.assertEqual("", S.porcelain(self.root))
        self.assertNotEqual(
            self.blob_id(self.path),
            digest.of_file(self.path),
            "the clean-file fast path is back: a git blob id is a second "
            "comparison domain, and `git add` alone then makes an in-sync "
            "artifact compare unequal to itself",
        )

    def test_the_blob_id_really_is_a_different_string(self):
        """Without this the assertion above could pass because the oracle is
        broken rather than because the domains differ."""
        blob = self.blob_id(self.path)
        self.assertEqual(40, len(blob))
        self.assertNotEqual("", blob)

    def test_the_module_can_reach_neither_git_nor_the_clock(self):
        """One domain means the digest consults nothing — the structural
        version of the assertion above, over the module's **imports** rather
        than over its prose, which is free to explain why git is absent."""
        import ast

        source = S.read_text(os.path.join(S.CORE_DIR, "digest.py"))
        imported = set()
        for node in ast.walk(ast.parse(source)):
            if isinstance(node, ast.Import):
                imported.update(alias.name.split(".")[0] for alias in node.names)
            elif isinstance(node, ast.ImportFrom) and node.module:
                imported.add(node.module.split(".")[0])
        self.assertEqual(
            {"hashlib"},
            imported,
            "digest.py reached for something; with no `paths`, `subprocess`, "
            "`os` or `time` in scope it cannot grow a git or mtime domain",
        )


class ReadOnlyTest(DigestFixture):
    def test_digesting_writes_nothing(self):
        S.git(self.root, "add", "AGENTS.md")
        S.git(self.root, "commit", "-q", "-m", "add agents")
        with S.unchanged_tree(self, self.root):
            digest.of_file(self.path)


if __name__ == "__main__":
    unittest.main()
